### ISSUE TITLE
All automated builds for feat/backend2 fail

### ISSUE THREAD

**Issue by antoninkriz** [fragaria/karmen#466]
After the backend has been separated from this repository in the branch `feat/backend2` the directory structure changed, which was not reflected in the Travis configuration.
This causes all Travis jobs to fail at the beginning no matter what.
Therefore neither FE tests nor linter is triggered, so the FE code starts to fill up with unprettified code.

**Comment by adamjezek98** [comment]
This will be resolved in https://github.com/fragaria/karmen/pull/496
